export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const REVIEWS_START = 'REVIEWS_START'
export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS'
export const REVIEWS_FAIL = 'REVIEWS_FAIL'


export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL'